In [1]:
import pandas as pd
import warnings
import numpy as np
warnings.filterwarnings('ignore')
df=pd.read_csv("C:\Downloads\dirty_cafe_sales.csv")


In [2]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02


In [3]:
df.dtypes

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

In [4]:
df.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='object')

In [5]:
df1=df[[ 'Item', 'Quantity', 'Price Per Unit', 'Total Spent']]

In [6]:
df1

,Item,Quantity,Price Per Unit,Total Spent
0,Coffee,2,2.0,4.0
1,Cake,4,3.0,12.0
2,Cookie,4,1.0,ERROR
3,Salad,2,5.0,10.0
4,Coffee,2,2.0,4.0
...,...,...,...,...
9995,Coffee,2,2.0,4.0
9996,NaN,3,NaN,3.0
9997,Coffee,4,2.0,8.0
9998,Cookie,3,NaN,3.0


In [7]:
df1.isnull().sum()

Item              333
Quantity          138
Price Per Unit    179
Total Spent       173
dtype: int64

In [8]:
df1.Item.unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', nan, 'ERROR', 'Juice', 'Tea'], dtype=object)

In [9]:
df1.Quantity.unique()	

array(['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan], dtype=object)

In [10]:
df1["Price Per Unit"].unique()

array(['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan, 'ERROR', 'UNKNOWN'],
      dtype=object)

In [11]:
df1['Total Spent'].unique()

array(['4.0', '12.0', 'ERROR', '10.0', '20.0', '9.0', '16.0', '15.0',
       '25.0', '8.0', '5.0', '3.0', '6.0', nan, 'UNKNOWN', '2.0', '1.0',
       '7.5', '4.5', '1.5'], dtype=object)

In [12]:
df1.replace({'ERROR':np.nan,'UNKNOWN':np.nan},inplace = True)

In [13]:
df.shape

(10000, 8)

In [14]:
df1.Item.unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', nan, 'Sandwich',
       'Juice', 'Tea'], dtype=object)

In [15]:
df1.Quantity.unique()

array(['2', '4', '5', '3', '1', nan], dtype=object)

In [16]:
df1["Price Per Unit"].unique()

array(['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan], dtype=object)

In [17]:
df1['Total Spent'].unique()

array(['4.0', '12.0', nan, '10.0', '20.0', '9.0', '16.0', '15.0', '25.0',
       '8.0', '5.0', '3.0', '6.0', '2.0', '1.0', '7.5', '4.5', '1.5'],
      dtype=object)

In [18]:
df1.dtypes

Item              object
Quantity          object
Price Per Unit    object
Total Spent       object
dtype: object

In [19]:
def datatype(x):
    return float(x)
a='11'
datatype(a)

11.0

In [20]:
df1["Price Per Unit"]=df1["Price Per Unit"].apply(datatype)

In [21]:
df1["Price Per Unit"].unique()

array([2. , 3. , 1. , 5. , 4. , 1.5, nan])

In [22]:
df1["Quantity"]=df1.Quantity.apply(datatype)

In [23]:
df1["Quantity"].unique()

array([ 2.,  4.,  5.,  3.,  1., nan])

In [24]:
df1['Total Spent']=df1['Total Spent'].apply(datatype)

In [25]:
df1

,Item,Quantity,Price Per Unit,Total Spent
0,Coffee,2.0,2.0,4.0
1,Cake,4.0,3.0,12.0
2,Cookie,4.0,1.0,NaN
3,Salad,2.0,5.0,10.0
4,Coffee,2.0,2.0,4.0
...,...,...,...,...
9995,Coffee,2.0,2.0,4.0
9996,NaN,3.0,NaN,3.0
9997,Coffee,4.0,2.0,8.0
9998,Cookie,3.0,NaN,3.0


In [26]:
df1.Item.unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', nan, 'Sandwich',
       'Juice', 'Tea'], dtype=object)

In [27]:
df1[df1['Item'] == 'Coffee']['Price Per Unit'].unique()

array([ 2., nan])

In [28]:
df1[df1['Item'] == 'Tea']['Price Per Unit'].unique()

array([1.5, nan])

In [29]:
df1[df1['Item'] == 'Cake']['Price Per Unit'].unique()

array([ 3., nan])

In [30]:
df1[df1['Item']=='Cookie']['Price Per Unit'].unique()

array([ 1., nan])

In [31]:
df1[df1['Item']=='Salad']['Price Per Unit'].unique()

array([ 5., nan])

In [32]:
df1[df1['Item']=='Smoothie']['Price Per Unit'].unique()

array([ 4., nan])

In [33]:
df1[df1['Item']=='Sandwich']['Price Per Unit'].unique()

array([ 4., nan])

In [34]:
df1[df1['Item']=='Juice']['Price Per Unit'].unique()

array([ 3., nan])

In [35]:
df1['Total Spent'].unique()

array([ 4. , 12. ,  nan, 10. , 20. ,  9. , 16. , 15. , 25. ,  8. ,  5. ,
        3. ,  6. ,  2. ,  1. ,  7.5,  4.5,  1.5])

In [36]:
df1['New_price']=df1['Total Spent']/df1['Quantity']

In [37]:
df1['New_price']

0       2.0
1       3.0
2       NaN
3       5.0
4       2.0
       ... 
9995    2.0
9996    1.0
9997    2.0
9998    1.0
9999    4.0
Name: New_price, Length: 10000, dtype: float64

In [38]:
df1

,Item,Quantity,Price Per Unit,Total Spent,New_price
0,Coffee,2.0,2.0,4.0,2.0
1,Cake,4.0,3.0,12.0,3.0
2,Cookie,4.0,1.0,NaN,NaN
3,Salad,2.0,5.0,10.0,5.0
4,Coffee,2.0,2.0,4.0,2.0
...,...,...,...,...,...
9995,Coffee,2.0,2.0,4.0,2.0
9996,NaN,3.0,NaN,3.0,1.0
9997,Coffee,4.0,2.0,8.0,2.0
9998,Cookie,3.0,NaN,3.0,1.0


In [39]:
df1['New_price']=df1["New_price"].fillna(df1["Price Per Unit"])

In [40]:
df1["New_price"].unique()

array([2. , 3. , 1. , 5. , 4. , 1.5, nan])

In [41]:
df1

,Item,Quantity,Price Per Unit,Total Spent,New_price
0,Coffee,2.0,2.0,4.0,2.0
1,Cake,4.0,3.0,12.0,3.0
2,Cookie,4.0,1.0,NaN,1.0
3,Salad,2.0,5.0,10.0,5.0
4,Coffee,2.0,2.0,4.0,2.0
...,...,...,...,...,...
9995,Coffee,2.0,2.0,4.0,2.0
9996,NaN,3.0,NaN,3.0,1.0
9997,Coffee,4.0,2.0,8.0,2.0
9998,Cookie,3.0,NaN,3.0,1.0


In [42]:
df1["New_Quantity"]=df1["Total Spent"]/df1['New_price']

In [43]:
df1["New_Quantity"]

0       2.0
1       4.0
2       NaN
3       2.0
4       2.0
       ... 
9995    2.0
9996    3.0
9997    4.0
9998    3.0
9999    3.0
Name: New_Quantity, Length: 10000, dtype: float64

In [44]:
df1["New_Quantity"]=df1["New_Quantity"].fillna(df1['Quantity'])

In [45]:
df1["New_Quantity"]

0       2.0
1       4.0
2       4.0
3       2.0
4       2.0
       ... 
9995    2.0
9996    3.0
9997    4.0
9998    3.0
9999    3.0
Name: New_Quantity, Length: 10000, dtype: float64

In [46]:
df1['New_Total']=df1['New_Quantity']*df1['New_price']

In [47]:
df1['New_Total']=df1['New_Total'].fillna(df1['Total Spent'])

In [48]:
df1['New_Total']

0        4.0
1       12.0
2        4.0
3       10.0
4        4.0
        ... 
9995     4.0
9996     3.0
9997     8.0
9998     3.0
9999    12.0
Name: New_Total, Length: 10000, dtype: float64

In [49]:
df1

,Item,Quantity,Price Per Unit,Total Spent,New_price,New_Quantity,New_Total
0,Coffee,2.0,2.0,4.0,2.0,2.0,4.0
1,Cake,4.0,3.0,12.0,3.0,4.0,12.0
2,Cookie,4.0,1.0,NaN,1.0,4.0,4.0
3,Salad,2.0,5.0,10.0,5.0,2.0,10.0
4,Coffee,2.0,2.0,4.0,2.0,2.0,4.0
...,...,...,...,...,...,...,...
9995,Coffee,2.0,2.0,4.0,2.0,2.0,4.0
9996,NaN,3.0,NaN,3.0,1.0,3.0,3.0
9997,Coffee,4.0,2.0,8.0,2.0,4.0,8.0
9998,Cookie,3.0,NaN,3.0,1.0,3.0,3.0


In [50]:
df1.New_price.unique()

array([2. , 3. , 1. , 5. , 4. , 1.5, nan])

In [51]:
df1.New_Quantity.unique()

array([ 2.,  4.,  5.,  3.,  1., nan])

In [52]:
df1.New_Total.unique()

array([ 4. , 12. , 10. , 20. ,  9. , 16. , 15. , 25. ,  8. ,  5. ,  3. ,
        6. ,  2. ,  nan,  1. ,  7.5,  4.5,  1.5])

In [53]:
df1.columns

Index(['Item', 'Quantity', 'Price Per Unit', 'Total Spent', 'New_price',
       'New_Quantity', 'New_Total'],
      dtype='object')

In [54]:
df2=df1.drop(columns=['Quantity', 'Price Per Unit', 'Total Spent'])

In [55]:
df2

,Item,New_price,New_Quantity,New_Total
0,Coffee,2.0,2.0,4.0
1,Cake,3.0,4.0,12.0
2,Cookie,1.0,4.0,4.0
3,Salad,5.0,2.0,10.0
4,Coffee,2.0,2.0,4.0
...,...,...,...,...
9995,Coffee,2.0,2.0,4.0
9996,NaN,1.0,3.0,3.0
9997,Coffee,2.0,4.0,8.0
9998,Cookie,1.0,3.0,3.0


In [56]:
df2.isna().sum()

Item            969
New_price        38
New_Quantity     38
New_Total        40
dtype: int64

In [57]:
df2.New_price.unique()

array([2. , 3. , 1. , 5. , 4. , 1.5, nan])

In [58]:
price_1=df2.New_price==1

In [59]:
df2.columns

Index(['Item', 'New_price', 'New_Quantity', 'New_Total'], dtype='object')

In [60]:
df2.dtypes

Item             object
New_price       float64
New_Quantity    float64
New_Total       float64
dtype: object

In [61]:
df2.Item.unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', nan, 'Sandwich',
       'Juice', 'Tea'], dtype=object)

In [62]:
cookie=df2.loc[price_1,['Item', 'New_price', 'New_Quantity', 'New_Total']]

In [63]:
cookie

,Item,New_price,New_Quantity,New_Total
2,Cookie,1.0,4.0,4.0
13,Cookie,1.0,5.0,5.0
26,Cookie,1.0,5.0,5.0
31,NaN,1.0,2.0,2.0
33,NaN,1.0,5.0,5.0
...,...,...,...,...
9956,Cookie,1.0,3.0,3.0
9976,Cookie,1.0,1.0,1.0
9982,Cookie,1.0,2.0,2.0
9996,NaN,1.0,3.0,3.0


In [64]:
cookie.shape

(1207, 4)

In [65]:
cookie.isna().sum()

Item            121
New_price         0
New_Quantity      2
New_Total         2
dtype: int64

In [66]:
cookie.Item.unique()

array(['Cookie', nan], dtype=object)

In [67]:
cookie['Item'].replace([np.nan],'Cookie',inplace=True)

In [68]:
cookie.shape

(1207, 4)

In [69]:
cookie.Item.unique()

array(['Cookie'], dtype=object)

In [70]:
cookie=cookie.dropna(subset=['New_Total', 'New_Quantity'],how='all')

In [71]:
cookie.shape

(1205, 4)

In [72]:
cookie.isnull().sum()

Item            0
New_price       0
New_Quantity    0
New_Total       0
dtype: int64

In [73]:
cookie.shape

(1205, 4)

In [74]:
price_15=df2.New_price==1.5

In [75]:
tea=df2.loc[price_15,['Item','New_price','New_Quantity','New_Total']]

In [76]:
tea.shape

(1200, 4)

In [77]:
tea.Item.unique()

array([nan, 'Tea'], dtype=object)

In [78]:
tea['Item'].replace([np.nan],'Tea',inplace=True)

In [79]:
tea.Item.unique()

array(['Tea'], dtype=object)

In [80]:
tea.isna().sum()

Item            0
New_price       0
New_Quantity    1
New_Total       1
dtype: int64

In [81]:
tea=tea.dropna(subset=['New_Total', 'New_Quantity'],how='all')

In [82]:
tea.isna().sum()

Item            0
New_price       0
New_Quantity    0
New_Total       0
dtype: int64

In [83]:
price_2=df2.New_price==2

In [84]:
coffee=df2.loc[price_2,['Item','New_price','New_Quantity','New_Total']]

In [85]:
coffee.shape

(1289, 4)

In [86]:
coffee.Item.unique()

array(['Coffee', nan], dtype=object)

In [87]:
coffee['Item'].replace([np.nan],'Coffee',inplace=True)

In [88]:
coffee=coffee.dropna(subset=['New_Quantity','New_Total'],how='all')

In [89]:
coffee.isna().sum()

Item            0
New_price       0
New_Quantity    0
New_Total       0
dtype: int64

In [90]:
price_3=df2.New_price==3

In [91]:
cake=df2.loc[price_3,['Item','New_price','New_Quantity','New_Total']]

In [92]:
cake['Item'].replace([np.nan],'Cake',inplace=True)

In [93]:
cake=cake.dropna(subset=['New_Quantity','New_Total'],how='all')

In [94]:
cake.isna().sum()

Item            0
New_price       0
New_Quantity    0
New_Total       0
dtype: int64

In [95]:
price_4=df2.New_price==4

In [96]:
sandwich=df2.loc[price_4,['Item','New_price','New_Quantity','New_Total']]

In [97]:
sandwich['Item'].replace([np.nan],'Sandwich',inplace=True)

In [98]:
sandwich=sandwich.dropna(subset=['New_Quantity','New_Total'],how='all')

In [99]:
sandwich.isna().sum()

Item            0
New_price       0
New_Quantity    0
New_Total       0
dtype: int64

In [100]:
price_5=df2.New_price==5

In [101]:
salad=df2.loc[price_5,['Item','New_price','New_Quantity','New_Total']]

In [102]:
salad['Item'].replace([np.nan],'Salad',inplace=True)

In [103]:
salad=salad.dropna(subset=['New_Quantity','New_Total'],how='all')

In [104]:
salad.isna().sum()

Item            0
New_price       0
New_Quantity    0
New_Total       0
dtype: int64

In [105]:
price_null=df2.New_price.isnull()==True

In [106]:
price_null

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997    False
9998    False
9999    False
Name: New_price, Length: 10000, dtype: bool

In [107]:
price_null=df2.loc[price_null,['Item','New_price','New_Quantity','New_Total']]

In [108]:
price_null


,Item,New_price,New_Quantity,New_Total
65,Sandwich,NaN,3.0,NaN
629,Cake,NaN,NaN,12.0
912,Sandwich,NaN,NaN,20.0
1008,Tea,NaN,NaN,3.0
1436,Tea,NaN,NaN,6.0
1482,Smoothie,NaN,NaN,16.0
1674,Tea,NaN,2.0,NaN
1761,NaN,NaN,4.0,NaN
2229,Sandwich,NaN,2.0,NaN
2289,NaN,NaN,4.0,NaN


In [109]:
price_null.dropna(subset=['Item'],inplace=True)

In [110]:
price_null.shape

(32, 4)

In [112]:
price_null['Item'].isna().sum()

np.int64(0)

In [115]:
def price(x):
    if x=="Cookie":
        return 1
    elif x=='Tea':
        return 1.5
    elif x=='Coffee':
        return 2
    elif x=='Cake':
        return 3
    elif x=='Juice':
        return 3
    elif x=='Smothie':
        return 4
    elif x=='Sandwich':
        return 4
    else:
        return 5
a='Cake'
price(a)
    

3

In [116]:
price_null['New_price']=price_null.Item.apply(price)

In [117]:
price_null['1 Quant']=price_null['New_Total']/price_null['New_price']

In [118]:
price_null

,Item,New_price,New_Quantity,New_Total,1 Quant
65,Sandwich,4.0,3.0,NaN,NaN
629,Cake,3.0,NaN,12.0,4.0
912,Sandwich,4.0,NaN,20.0,5.0
1008,Tea,1.5,NaN,3.0,2.0
1436,Tea,1.5,NaN,6.0,4.0
1482,Smoothie,5.0,NaN,16.0,3.2
1674,Tea,1.5,2.0,NaN,NaN
2229,Sandwich,4.0,2.0,NaN,NaN
2330,Salad,5.0,NaN,5.0,1.0
2585,Tea,1.5,3.0,NaN,NaN


In [119]:
price_null['New_Quantity']=price_null['1 Quant'].fillna(price_null['New_Quantity'])

In [120]:
price_null['New_Total']=price_null['New_Quantity']*price_null['New_price']

In [122]:
price_null.drop('1 Quant',axis=1,inplace=True)

In [123]:
price_null

,Item,New_price,New_Quantity,New_Total
65,Sandwich,4.0,3.0,12.0
629,Cake,3.0,4.0,12.0
912,Sandwich,4.0,5.0,20.0
1008,Tea,1.5,2.0,3.0
1436,Tea,1.5,4.0,6.0
1482,Smoothie,5.0,3.2,16.0
1674,Tea,1.5,2.0,3.0
2229,Sandwich,4.0,2.0,8.0
2330,Salad,5.0,1.0,5.0
2585,Tea,1.5,3.0,4.5


In [124]:
price_null.isna().sum()

Item            0
New_price       0
New_Quantity    0
New_Total       0
dtype: int64

In [125]:
price_null.dtypes

Item             object
New_price       float64
New_Quantity    float64
New_Total       float64
dtype: object

In [126]:
final_result=cookie._append([tea,price_2,price_3,price_4,price_5,price_null],ignore_index=True)

In [127]:
final_result

,Item,New_price,New_Quantity,New_Total,0
0,Cookie,1.0,4.0,4.0,NaN
1,Cookie,1.0,5.0,5.0,NaN
2,Cookie,1.0,5.0,5.0,NaN
3,Cookie,1.0,2.0,2.0,NaN
4,Cookie,1.0,5.0,5.0,NaN
...,...,...,...,...,...
42431,Cake,3.0,1.0,3.0,NaN
42432,Tea,1.5,5.0,7.5,NaN
42433,Tea,1.5,1.0,1.5,NaN
42434,Cake,3.0,1.0,3.0,NaN


In [128]:
final_result.shape

(42436, 5)

In [129]:
final_result.isnull().sum()

Item            40000
New_price       40000
New_Quantity    40000
New_Total       40000
0                2436
dtype: int64